<?php
declare(strict_types=1);
$pageTitle = 'About Harrison';
$currentNav = 'about';
require __DIR__ . '/includes/header.php';
?>
<section class="about-hero-dark"><div class="wrap"><div class="about-hero-grid"><div><p class="eyebrow">The people behind the numbers</p><h1>Clear thinking.<br><em>Human connection.</em></h1><p class="about-intro">The best advice does not start with a spreadsheet. It starts with understanding you.</p></div><div class="about-hero-image"><img src="assets/conversation.webp" width="1536" height="1024" fetchpriority="high" alt="Illustrative business conversation between two fictional professionals"><span>THE HARRISON<br><b>PERSPECTIVE</b></span></div></div></div></section>
  <section class="section light-section manifesto-section"><div class="wrap manifesto-grid"><p class="eyebrow eyebrow-dark">What we believe</p><div><h2>Behind every number is a bigger ambition.</h2><p>Your accounts tell a story. But they do not tell us what keeps you awake, what you are building towards or what success looks like to you. Those things deserve a conversation.</p><p>That is the perspective behind Harrison: practical expertise, clear communication and an interest in the whole picture.</p></div></div></section>
  <section class="section ink-section values-section"><div class="wrap"><div class="section-heading-row"><div><p class="eyebrow">What matters to us</p><h2>Three principles.<br><em>One way of working.</em></h2></div><p class="section-lead">Simple ideas, carried through every conversation and every piece of advice.</p></div><div class="values-grid"><article><span>01 / CLARITY</span><h3>Make it make sense.</h3><p>Useful advice is advice you can understand. We believe in clear conversations and a visible next step.</p></article><article><span>02 / CARE</span><h3>See the person.</h3><p>Every business and every individual has a different story. Taking the time to understand it is where trust begins.</p></article><article><span>03 / PERSPECTIVE</span><h3>Look a little further.</h3><p>Today’s responsibilities matter. So do tomorrow’s possibilities. Good accounting connects the detail with the bigger picture.</p></article></div></div></section>
  <section class="section light-section founder-section"><div class="wrap founder-grid"><div class="founder-image"><img src="assets/architecture.webp" width="1122" height="1402" loading="lazy" alt="Illustrative sunlit staircase curving upwards alongside a limestone building"><span class="vertical-label">A FRESH<br>PERSPECTIVE</span></div><div class="founder-copy"><p class="eyebrow eyebrow-dark">Working with Harrison</p><h2>A clear path.<br><em>A shared direction.</em></h2><p>Support should make your next step easier to see. We listen before advising, agree what matters and keep the conversation open as your priorities evolve.</p><div class="founder-quote">“The best relationship is one where the numbers become a little less intimidating.”</div><a class="link-dark" href="services.php">Discover our services <span>↗</span></a></div></div></section>
  <section class="section value-section about-process" aria-labelledby="approach-heading"><div class="wrap"><div class="value-intro"><div><p class="value-badge"><span>✦</span>How we work</p><h2 id="approach-heading">Good relationships<br><em>make good advice.</em></h2></div><p class="value-lead">No jargon theatre. No one-size-fits-all answers. Just thoughtful support that fits the reality of your life or business.</p></div><div class="value-grid"><article><span class="value-marker">✦</span><h3>Listen first.</h3><p>Understand the circumstances before discussing the solution.</p></article><article><span class="value-marker">✦</span><h3>Agree what matters.</h3><p>Make the scope, responsibilities and next steps clear.</p></article><article><span class="value-marker">✦</span><h3>Stay connected.</h3><p>Keep room for questions as your plans and priorities evolve.</p></article></div></div></section>
  <section class="cta-band"><div class="wrap cta-inner"><div><p class="eyebrow">Your next decision</p><h2>Make room for<br><em>what’s next.</em></h2></div><div><p>Start with a conversation that puts the whole picture on the table.</p><a class="btn btn-gold" href="contact.php">Let’s talk <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></a></div></div></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
