<?php
declare(strict_types=1);
$pageTitle = 'Financial clarity, fully considered';
$currentNav = 'home';
require __DIR__ . '/includes/header.php';
?>
<section class="v-hero" aria-labelledby="hero-heading"><div class="v-hero-bg"><img src="assets/conversation.webp" width="1536" height="1024" fetchpriority="high" alt="Illustrative business conversation in a light-filled office"></div><div class="v-hero-shade"></div><div class="v-hero-grid" aria-hidden="true"></div><div class="v-hero-signal" aria-hidden="true"><span></span><i></i><span></span></div><div class="v-hero-content wrap"><p class="v-kicker">Harrison / Financial partner</p><h1 id="hero-heading"><span class="hero-title-line">Financial clarity.</span><br><em class="hero-title-line hero-title-line--accent">Fully considered.</em></h1><p class="v-hero-copy">Harrison is the financial partner for business owners navigating growth. We bring structure to the numbers, context to the decisions and confidence to what comes next.</p><div class="v-actions"><a class="v-btn v-btn-solid" href="contact.php">Start the conversation</a><a class="v-btn v-btn-ghost" href="services.php">Explore services</a></div></div><div class="v-hero-insight" aria-label="Harrison point of view"><div class="v-insight-top"><span>Harrison / 01</span><span class="v-insight-arrow" aria-hidden="true">↗</span></div><strong>Structure before speed.</strong><p>See what matters now, then make the next move with intent.</p><div class="v-insight-tags"><span>Clarity</span><span>Context</span><span>Control</span></div></div><div class="v-hero-foot wrap"><span>Scroll to explore</span><span class="v-scroll-line" aria-hidden="true"></span><span>Clarity / Context / Control</span></div></section>
  <div class="ribbon-band" data-gold-ribbon="band" aria-hidden="true"></div>
  <section class="v-about v-dark-section" aria-labelledby="about-heading"><div class="v-shell"><div class="v-split-image"><img src="assets/architecture.webp" width="1122" height="1402" loading="lazy" alt="Sunlit modern architecture with a clear upward path"><div class="v-about-image-note" aria-hidden="true"><span class="v-about-image-index">01</span><span class="v-about-image-rule"></span><span>Perspective before prescription</span></div></div><div class="v-copy"><p class="v-label">About Harrison</p><h2 id="about-heading" data-scroll-lines><span class="reveal-line">Harrison is a <span class="gold-word">financial partner</span></span><span class="reveal-line">for business owners</span><span class="reveal-line">navigating <span class="gold-word">growth.</span></span><span class="reveal-line">We bring structure</span><span class="reveal-line">and <span class="gold-word">clarity</span> to the numbers</span><span class="reveal-line">so the next step feels clear.</span></h2><a class="v-text-link" href="about.php">Meet the Harrison perspective <span>→</span></a></div></div></section>
  <section class="v-industries v-dark-section" aria-label="Harrison clients"><div class="v-shell"><p>We Serve Clients Across Industries</p><div class="v-industry-grid" aria-label="Industries served"><div class="v-industry-track"><span>FOUNDERS</span><span>PROPERTY</span><span>CREATIVE</span><span>FAMILY BUSINESS</span><span>OPERATORS</span><span aria-hidden="true">FOUNDERS</span><span aria-hidden="true">PROPERTY</span><span aria-hidden="true">CREATIVE</span><span aria-hidden="true">FAMILY BUSINESS</span><span aria-hidden="true">OPERATORS</span></div></div></div></section>
<?php
$pinItems = [
  ['Company accounts', '', 'Accurate books. Timely reporting. Financials you can trust.', 'services/accounting-services.php', 'Learn more', 'conversation.webp', '30% 50%'],
  ['Bookkeeping & VAT', '', 'Smarter systems. Less manual work. Better visibility.', 'services/bookkeeping-services.php', 'Learn more', 'architecture.webp', '50% 65%'],
  ['Tax & self assessment', '', 'Confidence around what you owe and why.', 'services/personal-tax.php', 'Learn more', 'conversation.webp', '75% 40%'],
  ['Payroll & pensions', '', 'Reliable support for the people who keep you moving.', 'services/payroll.php', 'Learn more', 'architecture.webp', '50% 20%'],
  ['Business advisory', '', 'Financial guidance for smarter business decisions.', 'services/business-tax-advice.php', 'Learn more', 'conversation.webp', '55% 75%'],
  ['Starting a business', '', 'Build a thoughtful foundation for your next chapter.', 'services/company-secretarial-services.php', 'Learn more', 'architecture.webp', '50% 90%'],
];
$pinEyebrow = 'Our services';
$pinHeading = 'The financial engine<br><em>behind your business.</em>';
$pinHeadingId = 'services-heading';
$pinLead = 'We handle the numbers, build the systems and sit beside you as the business grows. Everything you need. Nothing you don’t.';
$pinDots = true;
$pinTypewriter = true;
$pinFooterLink = ['services.php', 'Explore all services'];
require __DIR__ . '/includes/pin-section.php';
?>
  <section class="v-serve v-dark-section" aria-labelledby="serve-heading"><canvas class="dot-field" data-dot-field aria-hidden="true"></canvas><div class="v-shell"><div class="v-section-intro"><p class="v-label">Who we serve</p><h2 id="serve-heading" class="v-typewriter-heading">Built for the people<br><em>building businesses.</em></h2><p>Harrison supports owners and leadership teams who need more than reports. They need a finance function that can keep up with the decisions they are making.</p></div><div class="v-serve-grid"><article><img src="assets/conversation.webp" width="1536" height="1024" loading="lazy" alt="Business owner in conversation"><div><h3>The owner</h3><p>The business has grown. The decisions have gotten bigger. The financial side needs to keep up.</p><a href="services/bookkeeping-services.php">How we handle your books <span>→</span></a></div></article><article><img src="assets/architecture.webp" width="1122" height="1402" loading="lazy" alt="Modern building detail"><div><h3>The builder</h3><p>Focused on what comes next and ready for the systems, structure and visibility to support it.</p><a href="contact.php">Inquire about our systems <span>→</span></a></div></article><article><img src="assets/conversation.webp" width="1536" height="1024" loading="lazy" alt="Business owners discussing plans"><div><h3>The operator</h3><p>Running a real business with real complexity and looking for clarity, not more spreadsheets.</p><a href="services/business-tax-advice.php">Explore advisory work <span>→</span></a></div></article><article><img src="assets/architecture.webp" width="1122" height="1402" loading="lazy" alt="Sunlit architecture detail"><div><h3>The leader</h3><p>Needs a financial partner who helps turn information into better decisions.</p><a href="about.php">Meet the Harrison team <span>→</span></a></div></article></div></div></section>
  <section class="v-founder" aria-labelledby="founder-heading"><div class="v-shell"><div class="v-founder-image"><img src="assets/conversation.webp" width="1536" height="1024" loading="lazy" alt="Friendly professional conversation"></div><div class="v-founder-copy"><p class="v-label">The Harrison difference</p><h2 id="founder-heading" class="v-typewriter-heading">Most firms show you<br>where you’ve been.<br><em>We look at what’s next.</em></h2><p>By combining accounting, tax, cash-flow visibility and strategic guidance, we give business owners the clarity they need to make confident decisions and move sustainably.</p><p class="v-quote">That’s the difference between keeping the books and building a financial engine for growth.</p></div></div></section>
  <section class="about-hero-dark home-who" aria-labelledby="home-who-heading"><div class="wrap"><div class="about-hero-grid"><div><p class="eyebrow">The people behind the numbers</p><h2 id="home-who-heading">Clear thinking.<br><em>Human connection.</em></h2><p class="about-intro">The best advice does not start with a spreadsheet. It starts with understanding you.</p><a class="v-text-link" href="about.php">More about who we are <span>→</span></a></div><div class="about-hero-image about-hero-particles" data-h-particles="assets/images/h-mark.json"><img src="assets/conversation.webp" width="1536" height="1024" loading="lazy" alt="Illustrative business conversation between two fictional professionals"><span>THE HARRISON<br><b>PERSPECTIVE</b></span></div></div></div></section>
  <section class="v-faq v-dark-section" aria-labelledby="faq-heading"><div class="v-shell"><div class="v-section-intro"><p class="v-label">Common questions</p><h2 id="faq-heading" class="v-typewriter-heading">Clear answers.</h2></div><div class="v-faq-list"><details><summary>Do I really need a finance partner, or should I just hire someone in-house?<span>+</span></summary><p>The right level of support depends on where your business is today. We can help you understand the most useful next step.</p></details><details><summary>How quickly will I see results?<span>+</span></summary><p>We start by making the current picture visible, then agree the changes that will make the biggest difference.</p></details><details><summary>What if my books are a mess?<span>+</span></summary><p>That is a normal place to start. We work through the detail calmly and build a reliable baseline.</p></details><details><summary>What does working with Harrison actually look like?<span>+</span></summary><p>A clear conversation, dependable routines and advice connected to the decisions in front of you.</p></details></div></div></section>
  <section class="v-cta"><div class="v-cta-image v-cta-mark" data-h-mark="assets/images/h-mark.json"><img class="h-mark-fallback" src="assets/images/h-mark.svg" width="265" height="260" alt="" loading="lazy"></div><div class="v-cta-overlay"></div><div class="v-cta-copy"><h2 class="v-typewriter-heading">Imagine knowing<br><em>exactly where you stand.</em></h2><p>Cash flow. Profitability. Priorities. What’s working. What’s not. And what comes next.</p><a class="v-btn v-btn-solid" href="contact.php">Start the conversation <span>↗</span></a></div></section>
<script type="module" src="<?= h(asset('assets/js/h-mark-3d.js')) ?>"></script>
<script type="module" src="<?= h(asset('assets/js/gold-ribbon.js')) ?>"></script>
<script type="module" src="<?= h(asset('assets/js/h-particles.js')) ?>"></script>
<?php require __DIR__ . '/includes/footer.php'; ?>
